#!/bin/bash
#SBATCH -n 16
#SBATCH -J pa2
#SBATCH -t1:00:00

modes=("a" "h" "m")
procs=(8 16)
sizes=(160 320 640 1280 2560 5120)

for proc in "${procs[@]}"; do
    for mode in "${modes[@]}"; do
        for size in "${sizes[@]}"; do
            echo "Running srun -n $proc ./transpose matrix-${size}.txt transposed.txt $mode $size"
            srun -n ${proc} ./transpose matrix-${size}.txt transposed.txt $mode $size
        done
    done
done
